image: node:latest

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - node_modules/

stages:
  - prepare
  - verify
  - test
  - publish

before_script:
  - VERSION=$([ ! -z $CI_COMMIT_TAG ] && echo ${CI_COMMIT_TAG} || echo ${CI_COMMIT_REF_NAME})
  - echo VERSION=$VERSION

codestyle:
  stage: verify
  script:
    - npm ci
    - npm run lint
    - npm audit

node:8:
  stage: test
  image: node:8
  only:
    - /^v\d+\.\d+\.\d+(-rc.\d+|)$/
  script:
    - npm i
    - npm run unit
  coverage: /^All files\s*\|\s*\d+\.*\d+\s*\|\s*(\d+\.*\d+)/

node:9:
  stage: test
  image: node:9
  only:
    - /^v\d+\.\d+\.\d+(-rc.\d+|)$/
  script:
    - npm i
    - npm run unit
  coverage: /^All files\s*\|\s*\d+\.*\d+\s*\|\s*(\d+\.*\d+)/

node:latest:
  stage: test
  image: node:latest
  script:
    - npm ci
    - npm run unit
  coverage: /^All files\s*\|\s*\d+\.*\d+\s*\|\s*(\d+\.*\d+)/

npm:
  stage: publish
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm ci
    - npm run prepare
    - npm publish
  environment:
    name: npm
    url: https://www.npmjs.com/package/${CI_PROJECT_NAME}
  when: manual
  only:
    - /^v\d+\.\d+\.\d+(-rc.\d+|)$/
